templates:
  streaming:
    cache_builders: 1
    smart_label: release.desc
    sync_mode: sync
    mdblist_list: https://mdblist.com/lists/plexmetamanager/<<key>>-movies
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/streaming/<<key_name_encoded>>.jpg

dynamic_collections:
  Streaming:
    type: custom
    data:
      appletv: Apple TV+
      disney: Disney+
      hbo-max: HBO Max
      hulu: Hulu
      netflix: Netflix
      amazon-prime-video: Prime Video
    title_format: <<key_name>> Movies
    template:
      - streaming
