libraries:

########################################
#   MUST MATCH THE PLEX LIBRARY NAME   #
########################################

  Movies:
    metadata_path:
    - folder: //config/collections/movies/
    - folder: //config/metadata/movies/
    settings:
      asset_directory: //config/assets/movies/
      overlay_path: //config/overlays/movies/
      remove_overlays: true
    report_path: /config/reports/Movies.yml

  Music:
    metadata_path:
    - folder: //config/metadata/music/
    settings:
      asset_directory: //config/assets/music/
    report_path: /config/reports/Music.yml

  Shows:
    metadata_path:
    - folder: //config/collections/shows/
    - folder: //config/metadata/shows/
    settings:
      asset_directory: //config/assets/shows/
      overlay_path: //config/overlays/shows/
      remove_overlays: true
    report_path: /config/reports/Shows.yml

playlist_files:
- folder: //config/playlists/

settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  asset_folders: true
  asset_depth: 1
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: true
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false

  show_unconfigured: true
  playlist_exclude_users:
webhooks:                            # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:

plex:
  url: http://192.168.70.11:32400
  token: SktLeBq2-1nZN3_YjZxx
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false

tmdb:                                                   # REQUIRED for the script to run
  apikey: b2cb2917c2c92cef2bc180346ec7f151
  language: en
  cache_expiration: 60
  region:

trakt:
  client_id: 0f2f2ac682fbb7d4ba30eb86ecd91313c3a4311dae25b51099236aa12c1bb516
  client_secret: fa28266c8e710e82bf1ad8d76a21b2ba47938f3b413b938b5702f65e224ea8dd
  pin:
  authorization:                          # everything below is autofilled by the script
    access_token: 24364e905c0c50ce6eab6444779f3d65154fec4bfdeeae5b41271d344c2eb7f2
    token_type: Bearer
    expires_in: 7889237
    refresh_token: a13fe50f980820719fbbf6ef5e934d7c7643deb0ea1689774e670c8f4bd6c0aa
    scope: public
    created_at: 1675964721
mdblist:
  apikey: 3aq477s3fgb4u4baunimjnygz
  cache_expiration: 60

# radarr:
#   url: http://192.168.40.40:7878
#   token: f21559379a044347bc31c013e8e1e6ac
#   add_missing: false
#   add_existing: false
#   root_folder_path: S:/movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   upgrade_existing: false

# sonarr:
#   url: http://192.168.40.40:8989
#   token: 0f9e7a36432843c08e1f4753ae7d86fe
#   add_missing: false
#   add_existing: false
#   root_folder_path: S:/shows
#   monitor: all
#   quality_profile: HD-1080p
#   language_profile: English
#   series_type: standard
#   season_folder: true
#   tag:
#   search: false
#   cutoff_search: false
#   sonarr_path:
#   plex_path:
#   upgrade_existing: false
