#####################
##     Example     ##
#####################

#  [TVDb number]: # [Name of show]
#    title: [Name of show]
#    alt_title: [it's sometimes also called...]
#    sort_title: [how to sort show]
#    url_poster: https://theposterdb.com/api/assets/[poster-number]

#################################################
##     Plex Auto-naming and Metadata Fixes     ##
#################################################

metadata:

  80252: # Flight of the Conchords
    url_poster: https://artworks.thetvdb.com/banners/posters/80252-2.jpg
    seasons:
      1:
        episodes:
          1:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330948.jpg
          2:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330949.jpg
          3:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330950.jpg
          4:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330951.jpg
          5:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330952.jpg
          6:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330953.jpg
          7:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330954.jpg
          8:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330955.jpg
          9:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330957.jpg
          10:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330958.jpg
          11:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330956.jpg
          12:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/330959.jpg
      2:
        episodes:
          1:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/417265.jpg
          2:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/422068.jpg
          3:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/422069.jpg
          4:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/422070.jpg
          5:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/422071.jpg
          6:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/433978.jpg
          7:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/433979.jpg
          8:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/443618.jpg
          9:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/443619.jpg
          10:
            url_poster: https://artworks.thetvdb.com/banners/episodes/80252/443620.jpg