#####################
##     Example     ##
#####################

#  [TVDb number]: # [Name of show]
#    title: [Name of show]
#    alt_title: [it's sometimes also called...]
#    sort_title: [how to sort show]
#    url_poster: https://theposterdb.com/api/assets/[poster-number]

#################################################
##     Plex Auto-naming and Metadata Fixes     ##
#################################################

metadata:

  404602: # Why Didn't They Ask Evans?
    seasons:
      1:
        episodes:
          1:
            title: Episode 1
          2:
            title: Episode 2
          3:
            title: Episode 3